### ISSUE TITLE
instantiateImpl not resolved

### ISSUE THREAD

**Issue by Berhug74** [android/kotlin-multiplatform-samples#17]
Hello!

I wanted to try Room in KMP to replace my existing implementation with SQLDelight. It is working on Android correctly, but in my project and in the Fruitties Sample, I am not able to test on a iOS device, because `instantiateImpl` (described also [here](https://developer.android.com/kotlin/multiplatform/room#ios)) is not resolved. 

Am I missing something?

Thanks :)

**Comment by VixonneN** [comment]
Some confusing thing, I have this extension giving me an error too, yet this project builds and works as it should.

**Comment by Berhug74** [comment]
Yes, I saw that it is generated in build folder. I managed to run the sample. 
I still have some issues in my personal project, on iOS only, but it might not by linked to `instanceImpl` directly. 

<img width="1352" alt="Capture d’écran 2024-05-02 à 18 02 29" src="https://github.com/android/kotlin-multiplatform-samples/assets/165804267/a264826b-dd03-4945-bb91-a84750809437">

**Comment by yenerm** [comment]
Hi, thanks for reporting this! I could replicate the error in Jellyfish but I have no problems building the app and running the iOS emulator using xCode. Can you verify if you have issues running the app?

**Comment by Berhug74** [comment]
Hi!

I am currently trying to make a feature-multi-module app instead of the "classic" local - domain - app
So, I tried to create one module `common-local` with the RoomDatabase and a module `feature-local` with DAOs and entities related to the feature.
I was facing issued with the DI due to the internal visibility of `instanceImpl`. I fix that.

I think I have a problem with this configuration. I tried on this sample, if I have shared -> common-local, it works on Android and iOS. But if I tried something like this:
shared -> common-local -> feature-local, it's not working anymore on iOS (but ok on Android):

<img width="788" alt="Capture d’écran 2024-05-02 à 20 30 10" src="https://github.com/android/kotlin-multiplatform-samples/assets/165804267/6eea709c-3c85-4348-93a3-5663dd8e5e75">

Is there sample for Room with a feature-multi-module approach (not in KMP)?

**Comment by Berhug74** [comment]
Hi again!
I made my repository public [here](https://github.com/Berhug74/mygpt). I can't figure out why on this repository, I still have an issue on iOS. The `RoomGptDatabase_InstantiateImpl.kt` is correctly generated but seems to be unresolved. 
<img width="1334" alt="Capture d’écran 2024-05-04 à 17 04 40" src="https://github.com/android/kotlin-multiplatform-samples/assets/165804267/d45cb913-a586-48fe-a8bb-b2fe01e154d0">

For iOS, this is the [actual method](See https://github.com/Berhug74/mygpt/blob/master/common/common-room/src/iosMain/kotlin/fr/hugobernardi/mygpt/common/room/RoomPlatformBuilder.kt) building the RoomDatabase.

The database is created from a [Koin module](https://github.com/Berhug74/mygpt/blob/master/common/common-room/src/commonMain/kotlin/fr/hugobernardi/mygpt/common/room/di/DiRoomModule.common.kt). Might be related to this?

It's ok on Android, it's running perfectly.

**Comment by Berhug74** [comment]
Hi again x2!
After further investigation, I think it might be linked to K2/KSP2. I tested my configuration in a brand new project.
It works with following versions:
ksp = "1.9.23-1.0.19"
kotlin = "1.9.23"

But doesn't work anymore (on iOS only) with:
ksp = "2.0.0-RC2-1.0.20"
kotlin = "2.0.0-RC2"

**Comment by sourabhgupta811** [comment]
@Berhug74 It did not work for me after using the mentioned kotlin and ksp versions. Did it work out of the box for you with these versions?
Kotlin - 1.9.23
ksp - 1.9.23-1.0.19
AGP - 8.4.0
Android studio version - Jellyfish | 2023.3.1

**Comment by Berhug74** [comment]
I use K2 because of Jetbrains Resources: https://github.com/JetBrains/compose-multiplatform/pull/4454

I tested on this [branch](https://github.com/Berhug74/mygpt/tree/test/k1) in my repo and I downgrade Kotlin to `1.9.23` and ksp `1.9.23-1.0.20`.
As expected, Jetbrains resources doesn't work anymore on iOS this time at runtime, but `instantiateImpl` is correctly resolved and the app is launched 🤯😅

**Comment by yenerm** [comment]
I double checked the project builds and runs as expected after a clean check out. I'll follow why Android Studio shows an error on Factory.native.kt:38 but this doesn't affect building and running the project.
