### ISSUE TITLE
schema json file not needed in github repo?

### ISSUE THREAD

**Issue by joreilly** [android/kotlin-multiplatform-samples#18]
Very minor thing but wondering if https://github.com/android/kotlin-multiplatform-samples/blob/main/Fruitties/shared/schemas/com.example.fruitties.database.AppDatabase/1.json should be included in github repo given that it's generated during build?

**Comment by yenerm** [comment]
ahh good catch, I'll validate it is not necessary and remove.

**Comment by zsmb13** [comment]
Actually, yes, these should be version controlled. See: https://developer.android.com/training/data-storage/room/migrating-db-versions#export-schemas

**Comment by yenerm** [comment]
ohh is it, json is regenerated when I rebuild the project?

**Comment by yenerm** [comment]
ok, I removed the json file but I will be adding it back with the next update.
