### ISSUE TITLE
Kotlin 2.0.0-RCX support?

### ISSUE THREAD

**Issue by joreilly** [android/kotlin-multiplatform-samples#23]
Hi,

Not sure if this is right place to ask this so feel free to close but wondering if it should be possible right now to use KMP version of Jetpack Room with Kotlin 2.0.0-RC version.....I tried with Fruities sample but couldn't get it to work.

**Comment by cartland** [comment]
This should be fixed in https://github.com/android/kotlin-multiplatform-samples/pull/28

* Updated to Kotlin 2.0.10
* Room 2.7.0-alpha06
  * https://developer.android.com/jetpack/androidx/releases/room#2.7.0-alpha06
